from __future__ import annotations

import logging
import os
from collections import defaultdict

from packages.schemas.python.state import (
    AnalysisState,
    AnalystMemo,
    Citation,
    DisclosureChange,
    EvidenceChunk,
    Holding,
    RiskScore,
)

logger = logging.getLogger(__name__)

MEMO_MODEL = "fincontext-reasoner"
MAX_EVIDENCE_ENTRIES = 20
MEMO_DISCLAIMER = (
    "This analysis is generated by an AI agent for informational purposes only. "
    "It does not constitute investment advice, financial advice, trading advice, "
    "or any other sort of advice. No buy, sell, hold, or short recommendations "
    "are made or implied."
)
MEMO_SYSTEM_PROMPT = (
    "Placeholder memo system prompt. Real prompt will be designed when Qwen-72B is integrated."
)
INFERENCE_GATEWAY_URL = os.getenv("INFERENCE_GATEWAY_URL", "http://localhost:8080")


def compute_risk_score(
    ticker: str,
    holding: Holding,
    related_changes: list[DisclosureChange],
    related_chunks: list[EvidenceChunk],
) -> RiskScore:
    """Build a placeholder risk score for a holding using related changes and evidence."""
    # TODO: replace with real risk computation based on disclosure severity and chunk relevance.
    citations = [build_citation(related_chunks[0])] if related_chunks else []
    return RiskScore(
        ticker=ticker,
        score=0.5,
        delta=0.0,
        confidence=0.7,
        top_drivers=["placeholder driver"],
        citations=citations,
        portfolio_impact=(
            f"{holding.name} ({ticker}) has placeholder portfolio impact pending full scoring logic."
        ),
    )


def group_changes_by_ticker(changes: list[DisclosureChange]) -> dict[str, list[DisclosureChange]]:
    """Group disclosure changes by ticker."""
    grouped: dict[str, list[DisclosureChange]] = defaultdict(list)
    for change in changes:
        grouped[change.ticker].append(change)
    return dict(grouped)


def group_chunks_by_ticker(chunks: list[EvidenceChunk]) -> dict[str, list[EvidenceChunk]]:
    """Group retrieved chunks by ticker."""
    grouped: dict[str, list[EvidenceChunk]] = defaultdict(list)
    for chunk in chunks:
        grouped[chunk.ticker].append(chunk)
    return dict(grouped)


def generate_memo_body(state: AnalysisState, risk_scores: list[RiskScore]) -> dict:
    """Return placeholder memo body fields for the visible memo output."""
    # TODO: replace with Qwen-72B call via Gateway for high-quality memo generation.
    # TODO: replace with gateway client when services/agent-api/app/clients/gateway.py is available.
    tickers = [score.ticker for score in risk_scores]
    return {
        "executive_summary": (
            f"Detected {len(state.disclosure_changes)} disclosure changes across "
            f"{len(tickers)} analyzed holdings in the retrieved filings."
        ),
        "affected_holdings": tickers,
        "watchlist_questions": [
            "Which newly described risks appear repeatedly across upcoming filings?"
        ],
        "limitations": (
            "This placeholder memo uses skeleton scoring, memo generation, and citation checks."
        ),
    }


def verify_citations(memo_body: dict, available_chunks: list[EvidenceChunk]) -> tuple[dict, float]:
    """Return the placeholder memo body unchanged with a placeholder citation pass rate."""
    # TODO: implement real citation verification — parse claims, match against chunks, strip
    # TODO: unsupported claims, compute real pass rate.
    return memo_body, 1.0


def build_evidence_table(
    chunks: list[EvidenceChunk],
    max_entries: int = MAX_EVIDENCE_ENTRIES,
) -> list[Citation]:
    """Map the top retrieved chunks into memo evidence citations."""
    return [build_citation(chunk) for chunk in chunks[:max_entries]]


def build_citation(chunk: EvidenceChunk) -> Citation:
    """Map an evidence chunk into the narrower citation schema."""
    return Citation(
        chunk_id=chunk.chunk_id,
        citation_anchor=chunk.citation_anchor,
        source_url=chunk.source_url,
        filed_at=chunk.filed_at,
        ticker=chunk.ticker,
        filing_type=chunk.filing_type,
        section=chunk.section,
    )


async def analyst_memo(state: AnalysisState) -> AnalysisState:
    """
    Generates risk scores per holding, writes the analyst memo via Qwen-72B,
    verifies every claim has a valid citation, and strips unsupported claims
    (stripping comes in a follow-up PR; this skeleton only reports pass rate).
    Falls back to a minimal valid memo on failure.
    """
    try:
        if not state.holdings:
            logger.warning("Analyst memo node fell back because holdings is empty.")
            return state.model_copy(
                update={
                    "memo": _build_fallback_memo(),
                    "risk_scores": [],
                    "citation_pass_rate": 0.0,
                    "partial": True,
                }
            )

        changes_by_ticker = group_changes_by_ticker(state.disclosure_changes)
        chunks_by_ticker = group_chunks_by_ticker(state.retrieved_chunks)

        risk_scores: list[RiskScore] = []
        for holding in state.holdings:
            ticker = holding.ticker
            risk_scores.append(
                compute_risk_score(
                    ticker=ticker,
                    holding=holding,
                    related_changes=changes_by_ticker.get(ticker, []),
                    related_chunks=chunks_by_ticker.get(ticker, []),
                )
            )

        memo_body = generate_memo_body(state, risk_scores)
        verified_memo_body, pass_rate = verify_citations(memo_body, state.retrieved_chunks)
        evidence_table = build_evidence_table(state.retrieved_chunks)

        memo = AnalystMemo(
            **verified_memo_body,
            disclosure_changes=state.disclosure_changes,
            risk_scores=risk_scores,
            evidence_table=evidence_table,
            disclaimer=MEMO_DISCLAIMER,
            citation_pass_rate=pass_rate,
        )

        return state.model_copy(
            update={
                "memo": memo,
                "risk_scores": risk_scores,
                "citation_pass_rate": pass_rate,
            }
        )
    except Exception as exc:
        logger.warning("Analyst memo node fell back to minimal memo: %s", exc)
        return state.model_copy(
            update={
                "memo": _build_fallback_memo(),
                "risk_scores": [],
                "citation_pass_rate": 0.0,
                "partial": True,
            }
        )


def _build_fallback_memo() -> AnalystMemo:
    """Build the minimal valid memo returned when memo generation is degraded."""
    return AnalystMemo(
        executive_summary="Memo generation degraded; returning a minimal placeholder memo.",
        affected_holdings=[],
        disclosure_changes=[],
        risk_scores=[],
        evidence_table=[],
        watchlist_questions=[],
        limitations="Fallback memo returned because analyst memo generation did not complete.",
        disclaimer=MEMO_DISCLAIMER,
        citation_pass_rate=0.0,
    )
